### ISSUE TITLE
sample docs not using pekko paradox plugin

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-samples#35]
A recent PR tried to change to use Pekko paradox plugin but the change seems not to work. The look and feel of https://pekko.apache.org/docs/pekko-samples/current/pekko-sample-cluster-scala/ is the standard Paradox look and feel as opposed to the Pekko variant (eg https://pekko.apache.org)

@sam-byng fyi

**Comment by sam-byng** [comment]
Will look at this this week
