### ISSUE TITLE
pekko-sample-cluster-java: Simple Cluster Example does not work

### ISSUE THREAD

**Issue by gamgiov** [apache/incubator-pekko-samples#73]
The Simple Cluster Example does not work.
Looking in depth at the ...../simple/App.java class file and its methods I noticed a wrong config property in the `private static void startup(int port)`  (see line 38)
The line is 
>     overrides.put("org.apache.pekko.remote.artery.canonical.port", port);
and should be changed to
>     overrides.put("pekko.remote.artery.canonical.port", port);

Reading the Artery Remoting documentation (https://pekko.apache.org/docs/pekko/current/remoting-artery.html) the right config property is "**pekko.remote.artery.canonical.port**"

After this change the Simple Cluster Example works very well !!!

**Comment by pjfanning** [comment]
Thanks @gamgiov for providing the description. I have created #74

**Comment by pjfanning** [comment]
PR merged
