### ISSUE TITLE
There is a configuration error in the startup settings of the pekko-sample-cluster-scala/stats  sample code

### ISSUE THREAD

**Issue by guoyu09403** [apache/incubator-pekko-samples#95]
`
  private def startup(role: String, port: Int): Unit = {

    // Override the configuration of the port when specified as program argument
    val config = ConfigFactory
      .parseString(s"""
      org.apache.pekko.remote.artery.canonical.port=$port // It should be  pekko.remote.artery.canonical.port
      org.apache.pekko.cluster.roles = [$role] //It should be pekko.cluster.roles
      """)
      .withFallback(ConfigFactory.load("stats"))

    ActorSystem[Nothing](RootBehavior(), "ClusterSystem", config)
  }
`

**Comment by pjfanning** [comment]
Thanks @guoyu09403 - I think #96 fixes this. Please reopen this if it doesn't help.
